-- Auto-generated by scripts/gen-yasal-metinler-seed.mjs - do not edit by hand
-- Turkish legal copy migrated from existing page.tsx files

INSERT INTO public.yasal_metinler (slug, baslik, baslik_en, meta_aciklama, meta_aciklama_en, icerik, icerik_en)
VALUES
(
  'kvkk',
  'KVKK Aydınlatma Metni',
  NULL,
  'MyLoungers KVKK aydınlatma metni — kişisel verilerin işlenmesi ve korunması hakkında bilgilendirme.',
  NULL,
  $yasal_kvkk$<h2>1. Kapsam ve Amaç</h2>
      <p class="mb-4 leading-relaxed">
        Bu metnin amacı, Reklamotv Bilişim Teknoloji Reklamcılık ve Organizasyon Hiz. San. ve Tic. Ltd.
        Şti. tarafından yönetilen www.myloungers.com adresinde yer alan internet sitesinin ve mobil
        uygulamasının kullanımı sırasında elde edilen veya üçüncü kişilerden alınan kişisel verilerin
        kullanımına ilişkin olarak, 6698 sayılı Kişisel Verilerin Korunması Kanunu'nun (KVKK) 10.
        maddesi ile getirilen aydınlatma yükümlülüğünün yerine getirilmesidir.
      </p>
      <p class="mb-4 leading-relaxed">
        My Loungers, sahil tesisleri, oteller ve beach club benzeri işletmelerin sunduğu şezlong
        hizmetleri ile bireysel kullanıcıları bir araya getirerek, kullanıcıların şezlong rezervasyonu
        yapmasını ve rezervasyon yaptığı işletmede yiyecek-içecek siparişi vermesini sağlayan bir
        platformdur.
      </p>
      <p class="mb-4 leading-relaxed">
        Reklamotv Bilişim Teknoloji Reklamcılık ve Organizasyon Hiz. San. ve Tic. Ltd. Şti., Kişisel
        Verilerin İşlenmesine İlişkin Aydınlatma Metninde gerekli görüldüğü takdirde değişiklik yapma
        hakkını saklı tutar. İşbu bilgilendirme metninin devamında Reklamotv Bilişim Teknoloji
        Reklamcılık ve Organizasyon Hiz. San. ve Tic. Ltd. Şti., My Loungers olarak anılacaktır.
      </p>

      <h2>2. Veri Sorumlusu ve Veri İşleyen</h2>
      <p class="mb-4 leading-relaxed">
        6698 sayılı Kişisel Verilerin Korunması Kanunu (KVKK) uyarınca, kişisel verileriniz, My Loungers
        tarafından veri sorumlusu sıfatıyla aşağıda belirtilen alanlarda toplanacak ve işlenecektir.
        Veri sorumlusu, Reklamotv Bilişim Teknoloji Reklamcılık ve Organizasyon Hiz. San. ve Tic. Ltd.
        Şti.'dir ve şirketin adresi ESENTEPE MAH. AKADEMİYOLU SK. TEKNOLOJİ GELİŞTİRME BÖLGESİ
        NO:10B/B01 SERDİVAN/SAKARYA'dır. Şirketin elektronik tebligat adresi: 25929-56263-22269
      </p>
      <p class="mb-4 leading-relaxed">
        Veri işleyen, veri sorumlusunun kişisel veri işlemek üzere yetkilendirdiği gerçek veya tüzel
        kişilerdir. My Loungers, işbu Aydınlatma Metninde belirtilen sınırlar çerçevesinde veri
        işleyenlerle kullanıcıların kişisel verilerinin güvenliğini sağlamak için gerekli idari ve teknik
        önlemleri almayı taahhüt eder.
      </p>

      <h2>3. Kişisel Verilerin Saklama Süresi</h2>
      <p class="mb-4 leading-relaxed">
        My Loungers tarafından elde edilen kişisel veriler, işlendikleri amaçlarla bağlantılı, sınırlı ve
        ölçülü şekilde ayrılarak saklanır. Bu kapsamda, kişisel veriler yalnızca belirtilen işleme
        amaçları doğrultusunda ve bu amaçlar için gerekli olan süre kadar muhafaza edilecektir.
      </p>
      <p class="mb-4 leading-relaxed">
        Uyuşmazlık hallerinde, yargı süreçlerinin sağlıklı bir şekilde devam edebilmesini sağlamak
        amacıyla kişisel veriler, ilgili mevzuatta belirtilen zamanaşımı süreleri boyunca saklanmaya
        devam edilecektir.
      </p>
      <p class="mb-4 leading-relaxed">
        Saklama süresinin sona ermesinin ardından, kişisel veriler KVKK ve ilgili mevzuata uygun şekilde
        silinir, yok edilir veya anonim hale getirilir.
      </p>

      <h2>4. İşlenen Kişisel Verilerin Kapsamı</h2>
      <p class="mb-4 leading-relaxed">
        My Loungers platformu içerisinde, hizmet alım kalitesinin, piyasa güveninin, platform
        güvenliğinin sağlanması ve korunması, My Loungers platformu tarafından sunulan hizmetlerin
        kullanıcı sözleşmesi çerçevesinde hedef kitleye ulaştırılabilmesi, kullanıcıların ve paydaşların
        hukuki, teknik ve ticari güvenliğinin sağlanması, planlama ve gelişim süreçlerinin yönetilmesi,
        pazarlama, reklam ve hedefleme amaçlarına uygun olarak 6698 sayılı KVKK'nın 5. ve 6.
        maddelerinde belirtilen kişisel veri işleme şartları ve amaçları çerçevesinde işlenmektedir.
      </p>

      <h2>5. İşlenen Kişisel Verilerin Aktarılması</h2>
      <p class="mb-4 leading-relaxed">
        My Loungers, KVKK'nın 8. ve 9. maddelerinde belirtilen kişisel veri işleme şartları ve
        amaçları çerçevesinde kullanıcılarına ait kişisel verileri aşağıdaki amaçlarla paylaşabilir:
      </p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>Kullanım koşulları ve üyelik sözleşmesinin gereklerini yerine getirmek</li>
        <li>Sunulan hizmetlerin ifasını sağlamak</li>
        <li>Kullanıcı deneyimini geliştirmek ve kişiselleştirmek</li>
        <li>My Loungers hizmetlerini geliştirmek</li>
        <li>Hataları ve sorunları gidermek</li>
        <li>Kullanıcı kimliklerini doğrulamak ve güvenliği artırmak</li>
        <li>Sistem performansını artırmak</li>
      </ul>
      <p class="mb-4 leading-relaxed">
        My Loungers kişisel verileri, yukarıdaki amaçları gerçekleştirmek için aşağıdaki taraflarla
        paylaşabilir:
      </p>
      <ol class="list-decimal list-inside ml-4 my-3 space-y-2">
        <li>
          <strong>Dış Kaynak Hizmet Sağlayıcılar ve İş Ortakları:</strong> Veri işleme, saklama ve
          güvenlik hizmetleri sağlayıcıları.
        </li>
        <li>
          <strong>Araştırma Şirketleri ve Ajanslar:</strong> Hizmetlerin kalitesini artırmaya yönelik
          analizler ve pazarlama çalışmaları.
        </li>
        <li>
          <strong>Ödeme Kuruluşları:</strong> Ad-soyad ve iletişim bilgileri doğrulaması gerçekleştirilmesi
          amacıyla.
        </li>
        <li>
          <strong>Yetkili Kamu Kurum ve Kuruluşları:</strong> Yasal zorunluluklar kapsamında gerekli
          bilgiler.
        </li>
      </ol>

      <h2>6. Kişisel Verilerin Toplanma Yöntemi ve Hukuki Sebebi</h2>
      <p class="mb-4 leading-relaxed">
        Kişisel veriler, My Loungers platformu üzerinden elektronik ortamda toplanmakta ve
        depolanmaktadır. Kişisel veriler, KVKK'nın 5. ve 6. maddelerinde belirtilen şartlar
        doğrultusunda; kullanıcıların kendilerinden, iş ortaklarından, siber kayıtlar üzerinden,
        iletilerden, mobil uygulamalardan, sosyal medya ve diğer kamuya açık mecralardan veya etkinlikler
        aracılığı ile toplanabilir.
      </p>
      <h3>6.1. Kullanıcıların Doğrudan Verdiği Veriler</h3>
      <p class="mb-4 leading-relaxed">
        Kullanıcıların, hizmetin ifası ve My Loungers platformunun kullanımı sırasında, kendi
        inisiyatifleri doğrultusunda verdikleri kişisel verilerdir. Bu veriler, ad-soyad, iletişim
        bilgileri, kimlik bilgileri, adres bilgileri gibi kullanıcının doğrudan verdiği tüm bilgileri
        kapsamaktadır.
      </p>
      <h3>6.2. Kullanım Sürecinde Elde Edilen Veriler</h3>
      <p class="mb-4 leading-relaxed">
        My Loungers platformunun kullanımı sırasında, belirli yazılım veya teknolojik araçlar aracılığıyla
        elde edilen kullanıcıların kullanım alışkanlıklarına ilişkin kişisel verilerdir. Örneğin,
        rezervasyon ve sipariş alışkanlıkları gibi veriler bu kapsamda yer almaktadır.
      </p>

      <h2>7. Mobil Uygulama İzinleri</h2>
      <p class="mb-4 leading-relaxed">
        My Loungers mobil uygulaması, hizmetin sağlanabilmesi için aşağıdaki cihaz izinlerini talep
        edebilir:
      </p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>
          <strong>Konum (Location):</strong> Yakınınızdaki tesisleri göstermek ve harita üzerinde konum
          bazlı arama yapabilmek için kullanılır. Bu izni reddedebilirsiniz; manuel bölge seçimi ile arama
          çalışmaya devam eder.
        </li>
        <li>
          <strong>Bildirimler (Notifications):</strong> Rezervasyon onayı, hatırlatma, ödeme
          bilgilendirmesi ve hizmete dair güncellemeleri iletmek için kullanılır. Bu izni
          reddedebilirsiniz.
        </li>
        <li>
          <strong>Kamera ve Galeri:</strong> Profil fotoğrafı yüklemek ve yorum süreçlerinde görsel
          paylaşımı yapabilmek için kullanılır. Bu izni reddedebilirsiniz.
        </li>
        <li>
          <strong>İnternet Erişimi:</strong> Uygulamanın temel fonksiyonlarının çalışması için zorunludur.
        </li>
      </ul>
      <p class="mb-4 leading-relaxed">
        Verilen izinler, cihaz ayarları (iOS Ayarlar / Android Ayarlar) üzerinden istediğiniz zaman geri
        çekilebilir veya değiştirilebilir.
      </p>

      <h2>8. Çocukların Korunması (18 Yaş Altı)</h2>
      <p class="mb-4 leading-relaxed">
        My Loungers, 18 yaşın altındaki kişilere yönelik bir hizmet sunmamakta ve 18 yaş altı
        kullanıcılardan bilerek kişisel veri toplamamaktadır. Platforma kayıt olurken kullanıcı, 18
        yaşını doldurmuş olduğunu beyan eder.
      </p>
      <p class="mb-4 leading-relaxed">
        18 yaşın altında olduğu tespit edilen kullanıcı hesapları derhal kapatılır ve bu hesaplara ait
        kişisel veriler ilgili mevzuat çerçevesinde silinir, yok edilir veya anonim hale getirilir.
      </p>
      <p class="mb-4 leading-relaxed">
        18 yaşın altındaki bir çocuğa ait kişisel verilerin platformumuzda yer aldığını düşünüyorsanız
        info@myloungers.com adresine başvurabilirsiniz. Bildirim üzerine ilgili veriler en geç 7 iş günü
        içerisinde imha edilir.
      </p>

      <h2>9. Hesap Silme ve Verilerin İmhası</h2>
      <p class="mb-4 leading-relaxed">
        Kullanıcılar, My Loungers hesaplarını ve hesaplarına bağlı tüm kişisel verilerin silinmesini
        istedikleri zaman talep edebilir.
      </p>
      <p class="mb-4 leading-relaxed">
        <strong>Hesap silme talebi şu şekilde yapılabilir:</strong>
      </p>
      <ol class="list-decimal list-inside ml-4 my-3 space-y-2">
        <li>
          Kayıtlı e-posta adresinizden info@myloungers.com adresine "Hesap Silme Talebi" konulu bir
          e-posta gönderilmesi.
        </li>
        <li>
          Talebin alınmasını takiben en geç 7 iş günü içerisinde hesabınız ve hesabınıza bağlı tüm veriler
          (profil bilgileri, rezervasyonlar, yorumlar ve sair kişisel veriler) kalıcı olarak silinir.
        </li>
        <li>Silme işlemi tamamlandığında kullanıcıya teyit e-postası gönderilir.</li>
      </ol>
      <p class="mb-4 leading-relaxed">
        Yasal saklama yükümlülüğü bulunan veriler (fatura, ödeme kayıtları, vergi mevzuatı kapsamındaki
        belgeler vb.), Türk vergi mevzuatı ve diğer ilgili mevzuat hükümleri çerçevesinde belirlenen
        sürelerle (10 yıla kadar) saklanmaya devam eder. Bu süre sonunda söz konusu veriler de imha
        edilir.
      </p>

      <h2>10. Veri Sahibinin Hakları (KVKK Madde 11)</h2>
      <p class="mb-4 leading-relaxed">
        6698 sayılı KVKK'nın 11. maddesi, kişisel veri sahiplerinin haklarını düzenlemektedir. My
        Loungers kullanıcıları, veri sahibi sıfatıyla bu maddede yer alan tüm haklara sahiptir.
        Kullanıcılar, taleplerini yazılı olarak Esentepe Mahallesi, Akademiyolu Sokak, Teknoloji
        Geliştirme Bölgesi, No:10B/B01 Serdivan/SAKARYA adresine veya info@myloungers.com adresine
        gönderebilir. My Loungers, talebi en geç otuz gün içerisinde ücretsiz olarak cevaplandırır.
      </p>
      <p class="mb-4 leading-relaxed">Veri sahibi olarak kullanıcılar, aşağıdaki haklara sahiptir:</p>
      <ol class="list-decimal list-inside ml-4 my-3 space-y-2">
        <li>Kişisel verilerinin işlenip işlenmediğini öğrenme</li>
        <li>Kişisel verileri işlenmişse buna ilişkin bilgi talep etme</li>
        <li>
          Kişisel verilerin işlenme amacını ve bu verilerin amacına uygun kullanılıp kullanılmadığını
          öğrenme
        </li>
        <li>Yurt içinde veya yurt dışında kişisel verilerin aktarıldığı üçüncü kişileri bilme</li>
        <li>
          Kişisel verilerin eksik veya yanlış işlenmiş olması hâlinde bunların düzeltilmesini isteme
        </li>
        <li>Kişisel verilerin silinmesini veya yok edilmesini isteme</li>
        <li>
          Kişisel verilerin düzeltilmesi, silinmesi ya da yok edilmesi hâlinde bu işlemlerin kişisel
          verilerin aktarıldığı üçüncü kişilere bildirilmesini isteme
        </li>
        <li>
          İşlenen verilerin münhasıran otomatik sistemler vasıtasıyla analiz edilmesi suretiyle, kişi
          aleyhine bir sonucun ortaya çıkmasına itiraz etme
        </li>
        <li>
          Kişisel verilerin kanuna aykırı olarak işlenmesi nedeniyle zarara uğraması hâlinde zararın
          giderilmesini talep etme
        </li>
      </ol>

      <h2>11. Kişisel Verilerin Güvenliğine Dair Önlemler</h2>
      <p class="mb-4 leading-relaxed">
        Kişisel veriler, My Loungers güvencesi altında korunur. Hukuka aykırı olarak veri işlenmesini ve
        erişilmesini engellemek, verilerin güvenliğini sağlamak amacıyla en üst seviye güvenlik
        tedbirleri ile teknik ve idari önlemler alınmaktadır. Kişisel veriler, işbu aydınlatma metninde
        belirtilen amaçlar ve KVKK hükümleri dışında kullanılmayacaktır.
      </p>
      <p class="mb-4 leading-relaxed">
        My Loungers platformunda bulunan bağlantılar (linkler) aracılığıyla farklı bir uygulama veya web
        sitesine yönlendirilmeniz durumunda, bu uygulama veya web sitesi tarafından işlenen veriler ve bu
        verilerin güvenliğine ilişkin olarak My Loungers herhangi bir sorumluluk taşımamaktadır.
      </p>

      <h2>12. Kişisel Verilerin Saklanması ve Depolanması</h2>
      <p class="mb-4 leading-relaxed">
        My Loungers platformu ile paylaştığınız kişisel veriler, KVKK mevzuatı çerçevesinde depolanmakta
        ve ilgili kanuni saklama süreleri veya My Loungers faaliyetlerinin gerektirdiği süre boyunca
        saklanmaktadır. Elde edilen kişisel veriler, My Loungers veya bağlı kuruluşları tarafından yurt
        içinde veya yurt dışında bulunan elektronik sistemlerde depolanabilir ve işlenebilir.
      </p>

      <h2>13. Açık Rıza Kapsamı</h2>
      <p class="mb-4 leading-relaxed">
        My Loungers platformuna kaydolan kullanıcı, işbu Aydınlatma Metni, KVKK ve ilgili ikincil
        mevzuat düzenlemeleri uyarınca; kişisel verilerin işlenmesi, korunması, üçüncü kişilerle
        paylaşılması ve aktarılması konularında, My Loungers faaliyetlerinin sürdürülmesi, yasal
        yükümlülüklerin yerine getirilmesi, hizmet kalitesinin artırılması, kullanıcı deneyiminin
        geliştirilmesi, pazarlama faaliyetlerinin yürütülmesi ve benzeri amaçlar doğrultusunda açık rıza
        vermektedir.
      </p>

      <h2>İletişim</h2>
      <p class="mb-4 leading-relaxed">
        <strong>E-posta:</strong> info@myloungers.com
      </p>
      <p class="mb-4 leading-relaxed">
        <strong>Adres:</strong> Esentepe Mah. Akademiyolu Sok. Teknoloji Geliştirme Bölgesi No:10B/B01
        Serdivan/SAKARYA
      </p>
      <p class="mb-4 leading-relaxed">
        <strong>Web:</strong> www.myloungers.com
      </p>$yasal_kvkk$,
  NULL
),
(
  'gizlilik',
  'Gizlilik Politikası',
  NULL,
  'MyLoungers gizlilik politikası — veri toplama, kullanım ve koruma ilkeleri.',
  NULL,
  $yasal_gizlilik$<h2>1. Amaç ve Kapsam</h2>
      <p class="mb-4 leading-relaxed">
        Bu Gizlilik Politikası, Reklamotv Bilişim Teknoloji Reklamcılık ve Organizasyon Hiz. San. ve
        Tic. Ltd. Şti. ("My Loungers") tarafından yönetilen www.myloungers.com adresinde yer
        alan internet sitesi ve mobil uygulama kullanıcılarının gizliliğini koruma amacı taşır. Politika,
        kullanıcıların kişisel verilerinin işlenmesine ilişkin esasları, verilerin saklanma yöntemlerini,
        paylaşım koşullarını ve kullanıcıların sahip olduğu hakları kapsamaktadır.
      </p>

      <h2>2. Toplanan Veriler</h2>
      <p class="mb-4 leading-relaxed">
        My Loungers tarafından toplanabilecek kişisel veri türleri şunlardır:
      </p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>
          <strong>Kimlik Bilgileri:</strong> İsim, soyisim, T.C. Kimlik Numarası, doğum tarihi, cinsiyet.
        </li>
        <li>
          <strong>İletişim Bilgileri:</strong> Telefon numarası, e-posta adresi, fiziksel adres.
        </li>
        <li>
          <strong>Finansal Bilgiler:</strong> Ödeme bilgileri, fatura bilgileri.
        </li>
        <li>
          <strong>Kullanıcı İşlem Bilgileri:</strong> Rezervasyon ve sipariş detayları, işlem geçmişi.
        </li>
        <li>
          <strong>Çerez Bilgileri:</strong> IP adresi, cihaz bilgileri, kullanıcı tercihlerine ilişkin
          veriler.
        </li>
      </ul>

      <h2>3. Kişisel Verilerin İşlenme Amaçları</h2>
      <p class="mb-4 leading-relaxed">Kişisel veriler, aşağıdaki amaçlarla işlenmektedir:</p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>Hizmetlerin sunulması ve kullanıcı hesaplarının yönetimi</li>
        <li>Rezervasyon ve ödeme işlemlerinin gerçekleştirilmesi</li>
        <li>Kullanıcı memnuniyetinin artırılması ve platformun geliştirilmesi</li>
        <li>Hukuki ve idari yükümlülüklerin yerine getirilmesi</li>
        <li>Güvenlik önlemlerinin alınması ve dolandırıcılıkların önlenmesi</li>
        <li>
          Pazarlama faaliyetlerinin yürütülmesi ve kullanıcıların tercihlerine uygun teklifler
          sunulması
        </li>
      </ul>

      <h2>4. Veri Toplama Yöntemleri</h2>
      <p class="mb-4 leading-relaxed">Kişisel veriler aşağıdaki yöntemlerle toplanabilir:</p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>
          <strong>Kullanıcı tarafından sağlanan bilgiler:</strong> Üyelik oluşturulması, My
          Loungers'ı kullanım sırasında sağlanan bilgiler.
        </li>
        <li>
          <strong>Otomatik yöntemler:</strong> Çerezler, log kayıtları ve cihaz bilgileri aracılığıyla
          toplanan veriler.
        </li>
        <li>
          <strong>Üçüncü taraflardan alınan veriler:</strong> Ödeme kuruluşları veya iş ortakları
          aracılığıyla alınan bilgiler.
        </li>
      </ul>

      <h2>5. Verilerin Paylaşımı</h2>
      <p class="mb-4 leading-relaxed">
        My Loungers, kişisel verilerinizi yalnızca aşağıdaki koşullarda ve amaçlarla paylaşabilir:
      </p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>
          <strong>İş Ortakları:</strong> Hizmetlerin ifası ve kullanıcı destek süreçlerinin yürütülmesi
          amacıyla.
        </li>
        <li>
          <strong>Yetkili Kamu Kurum ve Kuruluşları:</strong> Yasal yükümlülüklerin yerine getirilmesi
          amacıyla.
        </li>
        <li>
          <strong>Ödeme Kuruluşları:</strong> Kimlik doğrulama ve ödeme işlemlerinin güvenli bir şekilde
          gerçekleştirilmesi amacıyla.
        </li>
        <li>
          <strong>Hizmet Sağlayıcılar:</strong> Veri depolama, güvenlik ve analiz hizmetleri sağlanması
          amacıyla.
        </li>
      </ul>

      <h2>6. Kişisel Verilerin Saklanma Süresi</h2>
      <p class="mb-4 leading-relaxed">
        Kişisel veriler, işlendikleri amaç doğrultusunda gerekli olan süre boyunca saklanır. Süre sonunda
        veriler, yasal düzenlemelere uygun şekilde silinir, yok edilir veya anonim hale getirilir. Yasal
        zorunluluk durumunda, zamanaşımı süresi boyunca veriler saklanabilir.
      </p>

      <h2>7. Çerezler</h2>
      <p class="mb-4 leading-relaxed">
        My Loungers, kullanıcı deneyimini iyileştirmek, platformun güvenliğini sağlamak ve
        kişiselleştirilmiş hizmetler sunmak amacıyla çerezlerden yararlanır. Kullanıcılar, tarayıcı
        ayarlarını değiştirerek çerezlerin kullanımını sınırlayabilir veya devre dışı bırakabilir. Çerez
        kullanımına ilişkin detaylar Çerez Politikası bölümümüzde yer almaktadır.
      </p>

      <h2>8. Veri Güvenliği Önlemleri</h2>
      <p class="mb-4 leading-relaxed">
        Kişisel verilerinizin gizliliğini ve güvenliğini korumak için gerekli tüm teknik ve idari
        önlemler alınmaktadır.
      </p>

      <h2>9. Mobil Uygulama İzinleri</h2>
      <p class="mb-4 leading-relaxed">
        My Loungers mobil uygulaması, hizmetin sağlanabilmesi için aşağıdaki cihaz izinlerini talep
        edebilir:
      </p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>
          <strong>Konum (Location):</strong> Yakınınızdaki tesisleri göstermek ve harita üzerinde konum
          bazlı arama yapabilmek için kullanılır. Bu izni reddedebilirsiniz; manuel bölge seçimi ile arama
          çalışmaya devam eder.
        </li>
        <li>
          <strong>Bildirimler (Notifications):</strong> Rezervasyon onayı, hatırlatma, ödeme
          bilgilendirmesi ve hizmete dair güncellemeleri iletmek için kullanılır. Bu izni
          reddedebilirsiniz.
        </li>
        <li>
          <strong>Kamera ve Galeri:</strong> Profil fotoğrafı yüklemek ve yorum süreçlerinde görsel
          paylaşımı yapabilmek için kullanılır. Bu izni reddedebilirsiniz.
        </li>
        <li>
          <strong>İnternet Erişimi:</strong> Uygulamanın temel fonksiyonlarının çalışması için
          zorunludur.
        </li>
      </ul>
      <p class="mb-4 leading-relaxed">
        Verilen izinler, cihaz ayarları (iOS Ayarlar / Android Ayarlar) üzerinden istediğiniz zaman geri
        çekilebilir veya değiştirilebilir.
      </p>

      <h2>10. Üçüncü Taraf Servisler</h2>
      <p class="mb-4 leading-relaxed">
        My Loungers, hizmetin sağlanabilmesi için aşağıdaki üçüncü taraf servislerini kullanmaktadır. Bu
        servisler, kendi gizlilik politikaları çerçevesinde veri işlemektedir:
      </p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>
          <strong>Apple Sign-In:</strong> Apple kullanıcılarının kimlik doğrulaması için kullanılır.
          Apple, e-posta adresini gizleme seçeneği sunar.
        </li>
        <li>
          <strong>Google Sign-In:</strong> Google kullanıcılarının kimlik doğrulaması için kullanılır.
        </li>
        <li>
          <strong>Supabase (Frankfurt, Almanya):</strong> Kullanıcı verilerinin güvenli şekilde
          depolanması ve kimlik doğrulama hizmeti için kullanılır. AB veri merkezinde saklanır.
        </li>
        <li>
          <strong>Paratika (Asseco SEE):</strong> Ödeme işlemlerinin güvenli şekilde gerçekleştirilmesi
          için kullanılır. PCI-DSS standartlarına uygundur.
        </li>
      </ul>
      <p class="mb-4 leading-relaxed">
        My Loungers, üçüncü taraf servislerin gizlilik uygulamalarından sorumlu değildir. Bu servislerin
        gizlilik politikalarını ayrıca incelemeniz önerilir.
      </p>

      <h2>11. Çocukların Korunması (18 Yaş Altı)</h2>
      <p class="mb-4 leading-relaxed">
        My Loungers, 18 yaşın altındaki kişilere yönelik bir hizmet sunmamakta ve 18 yaş altı
        kullanıcılardan bilerek kişisel veri toplamamaktadır. Platforma kayıt olurken kullanıcı, 18
        yaşını doldurmuş olduğunu beyan eder.
      </p>
      <p class="mb-4 leading-relaxed">
        18 yaşın altında olduğu tespit edilen kullanıcı hesapları derhal kapatılır ve bu hesaplara ait
        kişisel veriler ilgili mevzuat çerçevesinde silinir, yok edilir veya anonim hale getirilir.
      </p>
      <p class="mb-4 leading-relaxed">
        18 yaşın altındaki bir çocuğa ait kişisel verilerin platformumuzda yer aldığını düşünüyorsanız
        info@myloungers.com adresine başvurabilirsiniz. Bildirim üzerine ilgili veriler en geç 7 iş günü
        içerisinde imha edilir.
      </p>

      <h2>12. Hesap Silme ve Verilerin İmhası</h2>
      <p class="mb-4 leading-relaxed">
        Kullanıcılar, My Loungers hesaplarını ve hesaplarına bağlı tüm kişisel verilerin silinmesini
        istedikleri zaman talep edebilir.
      </p>
      <p class="mb-4 leading-relaxed">
        <strong>Hesap silme talebi şu şekilde yapılabilir:</strong>
      </p>
      <ol class="list-decimal list-inside ml-4 my-3 space-y-2">
        <li>
          Kayıtlı e-posta adresinizden info@myloungers.com adresine "Hesap Silme Talebi"
          konulu bir e-posta gönderilmesi.
        </li>
        <li>
          Talebin alınmasını takiben en geç 7 iş günü içerisinde hesabınız ve hesabınıza bağlı tüm veriler
          (profil bilgileri, rezervasyonlar, yorumlar ve sair kişisel veriler) kalıcı olarak silinir.
        </li>
        <li>Silme işlemi tamamlandığında kullanıcıya teyit e-postası gönderilir.</li>
      </ol>
      <p class="mb-4 leading-relaxed">
        Yasal saklama yükümlülüğü bulunan veriler (fatura, ödeme kayıtları, vergi mevzuatı kapsamındaki
        belgeler vb.), Türk vergi mevzuatı ve diğer ilgili mevzuat hükümleri çerçevesinde belirlenen
        sürelerle (10 yıla kadar) saklanmaya devam eder. Bu süre sonunda söz konusu veriler de imha
        edilir.
      </p>

      <h2>13. Kullanıcı Hakları</h2>
      <p class="mb-4 leading-relaxed">
        Kullanıcılar, 6698 sayılı Kişisel Verilerin Korunması Kanunu'nun 11. maddesi kapsamında;
        kişisel verilerinin işlenip işlenmediğini öğrenme, işlenmişse buna ilişkin bilgi talep etme,
        verilerinin işlenme amacını ve amacına uygun kullanılıp kullanılmadığını öğrenme, kişisel
        verilerinin yurt içinde veya yurt dışında aktarıldığı üçüncü kişileri bilme, kişisel verilerinin
        eksik veya yanlış işlenmiş olması hâlinde bunların düzeltilmesini isteme, kişisel verilerinin
        kanunda öngörülen şartlar çerçevesinde silinmesini veya yok edilmesini isteme, kişisel verilerinin
        düzeltilmesi, silinmesi veya yok edilmesi hâlinde bu işlemlerin kişisel verilerinin aktarıldığı
        üçüncü kişilere bildirilmesini isteme, işlenen verilerin münhasıran otomatik sistemler vasıtasıyla
        analiz edilmesi suretiyle kendisi aleyhine bir sonucun ortaya çıkmasına itiraz etme ve kişisel
        verilerinin kanuna aykırı olarak işlenmesi sebebiyle zarara uğraması hâlinde zararın giderilmesini
        talep etme haklarına sahiptir.
      </p>

      <h2>14. Politika Güncellemeleri</h2>
      <p class="mb-4 leading-relaxed">
        My Loungers, bu Gizlilik Politikasını her zaman değiştirme hakkını saklı tutar. Güncellemeler,
        platform üzerinde yayınlandığı tarihten itibaren geçerlilik kazanır.
      </p>

      <h2>15. İletişim Bilgileri</h2>
      <p class="mb-4 leading-relaxed">
        Kişisel verilerinizin işlenmesiyle ilgili talepleriniz ve sorularınız için bizimle iletişime
        geçebilirsiniz:
      </p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>
          <strong>E-posta:</strong> info@myloungers.com
        </li>
        <li>
          <strong>Posta Adresi:</strong> Esentepe Mah. Akademiyolu Sok. No:10B/B01 Serdivan/Sakarya
        </li>
        <li>
          <strong>Web:</strong> www.myloungers.com
        </li>
      </ul>

      <h2>16. Üçüncü Taraf Bağlantıları</h2>
      <p class="mb-4 leading-relaxed">
        My Loungers platformunda yer alan üçüncü taraf sitelere yapılan yönlendirmeler, ilgili sitelerin
        kendi gizlilik politikaları tarafından düzenlenir. Bu sitelerin gizlilik uygulamaları üzerinde My
        Loungers'ın herhangi bir sorumluluğu bulunmamaktadır.
      </p>

      <h2>17. Yasal Uyum ve Uyuşmazlıkların Çözümü</h2>
      <p class="mb-4 leading-relaxed">
        My Loungers, tüm faaliyetlerinde yürürlükteki mevzuata uyum göstermeyi taahhüt eder. İşbu
        Gizlilik Politikasından doğabilecek uyuşmazlıklar, Türk hukuku çerçevesinde Sakarya Mahkemeleri
        ve İcra Daireleri tarafından çözümlenecektir.
      </p>$yasal_gizlilik$,
  NULL
),
(
  'kullanim-kosullari',
  'Kullanıcı Üyelik Sözleşmesi',
  NULL,
  'MyLoungers kullanıcı üyelik sözleşmesi — platform kullanım şartları ve yükümlülükler.',
  NULL,
  $yasal_kullanim_kosullari$<p class="mb-4 leading-relaxed">
        My Loungers'a kaydolmadan önce Kullanıcı Üyelik Sözleşmesi'ni dikkatlice okumanız
        gerekmektedir. Sitemize veya uygulamamıza kaydolmanız halinde, Kullanıcı Üyelik
        Sözleşmesi'nde belirtilen şartları peşinen kabul etmiş ve site kurallarına uymayı taahhüt
        etmiş sayılacaksınız.
      </p>
      <p class="mb-4 leading-relaxed">
        My Loungers platformuna kaydolan her kullanıcı, aşağıda belirtilen şartları okuyup kabul
        etmiş sayılmaktadır. Bu hizmet, Reklamotv Bilişim Teknoloji Reklamcılık ve Organizasyon Hiz.
        San. ve Tic. Ltd. Şti. tarafından sağlanan, işletmeler ile şahısları buluşturmayı amaçlayan bir
        aracılık hizmetidir.
      </p>

      <h2>1. Madde - Taraflar ve Tanımlar</h2>
      <h3>1.1. Taraflar</h3>
      <p class="mb-4 leading-relaxed">
        Bu sözleşme, bir tarafta Reklamotv Bilişim Teknoloji Reklamcılık ve Organizasyon Hiz. San. ve
        Tic. Ltd. Şti. ("Şirket"), diğer tarafta My Loungers web sitesi veya mobil uygulamasını
        ("Platform") kullanan bireysel kullanıcı ("Kullanıcı") arasında akdedilmiştir.
      </p>
      <p class="mb-4 leading-relaxed">
        <strong>Şirket:</strong>
      </p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>
          <strong>Vergi Dairesi:</strong> Gümrükönü Vergi Dairesi Müdürlüğü
        </li>
        <li>
          <strong>Vergi Kimlik Numarası (VKN):</strong> 7340777763
        </li>
        <li>
          <strong>Adres:</strong> Esentepe Mah. Akademiyolu Sok. Teknoloji Geliştirme Bölgesi No:10B/B01
          Serdivan/SAKARYA
        </li>
        <li>
          <strong>E-posta:</strong> info@myloungers.com
        </li>
      </ul>
      <p class="mb-4 leading-relaxed">
        <strong>Kullanıcı:</strong> herhangi bir elektronik ortam veya mobil cihaz üzerinden My
        Loungers platformuna kaydolan gerçek kişiyi ifade eder. Kullanıcı, platform üzerinden şezlong
        rezervasyonu yapabilir, işletmelerin menülerinden yiyecek ve içecek siparişi verebilir ve bakiye
        yükleyerek bu hizmetlerden faydalanabilir.
      </p>

      <h3>1.2. Tanımlar</h3>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>
          <strong>Platform:</strong> My Loungers adı altında faaliyet gösteren, işletmeler ile bireysel
          kullanıcıları buluşturarak şezlong rezervasyonu, yiyecek ve içecek siparişleri için aracılık
          yapan çevrimiçi hizmet platformu.
        </li>
        <li>
          <strong>Kullanıcı:</strong> Platforma üye olarak şezlong rezervasyonu yapan, yiyecek-içecek
          hizmetlerinden yararlanan gerçek kişi.
        </li>
        <li>
          <strong>İşletme:</strong> Platform üzerinden şezlong rezervasyonu yapılabilen otel, beach club
          ve benzeri ticari işletmeler.
        </li>
        <li>
          <strong>Rezervasyon:</strong> Kullanıcı tarafından Platform aracılığıyla bir şezlong veya
          hizmetin belirli bir tarih ve saat için ayırtılması işlemi.
        </li>
        <li>
          <strong>Sipariş:</strong> Kullanıcı tarafından işletmenin menü sekmesi aracılığıyla verilen
          yiyecek ve/veya içecek siparişleri.
        </li>
        <li>
          <strong>Bakiye:</strong> Kullanıcının Platform üzerinde gerçekleştireceği ödemeler için siteye
          yüklediği ön ödemeli miktar.
        </li>
        <li>
          <strong>Komisyon:</strong> Platform tarafından, işletmelerden alınan %7 oranındaki hizmet
          bedeli.
        </li>
        <li>
          <strong>Ödeme Sağlayıcısı:</strong> Paratika Elektronik Ödeme ve Dağıtım Hizmetleri A.Ş.
        </li>
      </ul>

      <h2>2. Madde - Sözleşmenin Amacı ve Kapsamı</h2>
      <h3>2.1. Sözleşmenin Amacı</h3>
      <p class="mb-4 leading-relaxed">
        Bu sözleşme, My Loungers platformuna üye olan kullanıcılar ile Şirket arasında, platform
        aracılığıyla sunulan aracılık hizmetlerinin kullanımına ilişkin tarafların hak ve
        yükümlülüklerini düzenlemeyi amaçlar.
      </p>
      <h3>2.2. Sözleşmenin Kapsamı</h3>
      <p class="mb-4 leading-relaxed">
        Kullanıcıların My Loungers platformu aracılığıyla, işletmeler tarafından sunulan şezlong
        rezervasyonu ve yiyecek-içecek siparişi hizmetlerini satın almaları için gerekli koşullar
        düzenlenir. Platformun, yalnızca kullanıcılar ve işletmeler arasında bir aracılık hizmeti
        sunduğu, hizmetin ifasından doğrudan sorumlu olmadığı belirtilir.
      </p>
      <h3>2.3. Yasal Dayanak</h3>
      <p class="mb-4 leading-relaxed">
        Bu sözleşme, Tüketicinin Korunması Hakkında Kanun, Mesafeli Sözleşmeler Yönetmeliği, Türk Borçlar
        Kanunu ve ilgili diğer mevzuat hükümleri çerçevesinde hazırlanmıştır.
      </p>

      <h2>3. Madde - Kullanıcı Kaydı ve Üyelik Koşulları</h2>
      <h3>3.1. Kayıt Süreci</h3>
      <p class="mb-4 leading-relaxed">
        Kullanıcıların My Loungers platformunu kullanabilmesi için platforma üye olmaları zorunludur.
        Kullanıcı, isim ve soyisim, geçerli bir e-posta adresi, telefon numarası ve belirlenmiş bir şifre
        bilgilerini doğru ve eksiksiz girmesi gerekir. Kullanıcı, dilerse Apple Sign-In veya Google
        Sign-In hizmetleri aracılığıyla da platforma kayıt olabilir.
      </p>
      <h3>3.2. Doğrulama Süreci</h3>
      <p class="mb-4 leading-relaxed">
        Kayıt işleminin tamamlanabilmesi için, e-posta adresine bir doğrulama bağlantısı, telefon
        numarasına ise bir doğrulama kodu gönderilir. Kullanıcı, her iki doğrulamayı başarıyla tamamladıktan
        sonra üyelik işlemi tamamlanır.
      </p>
      <h3>3.3. Kullanıcı Bilgilerinin Doğruluğu</h3>
      <p class="mb-4 leading-relaxed">
        Kullanıcı, kayıt esnasında verdiği tüm bilgilerin doğru, eksiksiz ve güncel olduğunu taahhüt eder.
        Şirket, verilen bilgilerin yanlış veya eksik olması durumunda kullanıcı üyeliğini iptal etme veya
        askıya alma hakkını saklı tutar.
      </p>
      <h3>3.4. Üyelik Hesabının Güvenliği</h3>
      <p class="mb-4 leading-relaxed">
        Kullanıcı, üyelik sırasında oluşturduğu şifrenin gizliliğini korumakla yükümlüdür. Kullanıcı
        hesabının izinsiz kullanımından doğabilecek her türlü zarar ve kayıptan kullanıcı sorumlu olup,
        Şirket bu durumlardan sorumlu tutulamaz.
      </p>
      <h3>3.5. Üyelik Koşulları</h3>
      <p class="mb-4 leading-relaxed">
        Kullanıcı, platforma üye olurken ve üyeliği süresince yasal olarak platforma üye olabilecek reşit
        yaşta (18 yaş ve üzeri) olduğunu, platformda belirtilen kurallara, yasalara ve sözleşmelere
        uygun hareket edeceğini kabul eder.
      </p>
      <p class="mb-4 leading-relaxed">
        Platform, 18 yaşın altındaki kişilere yönelik bir hizmet sunmamakta ve 18 yaş altı kullanıcılardan
        bilerek kişisel veri toplamamaktadır. 18 yaşın altında olduğu tespit edilen kullanıcı hesapları
        derhal kapatılır ve bu hesaplara ait veriler silinir.
      </p>
      <h3>3.6. Üyelik İptali ve Hesap Silme</h3>
      <p class="mb-4 leading-relaxed">
        Kullanıcı, istediği zaman üyelik hesabını iptal etme ve kendisine ait tüm kişisel verilerin
        silinmesini talep etme hakkına sahiptir.
      </p>
      <p class="mb-4 leading-relaxed">
        <strong>Hesap silme talebi şu şekilde yapılabilir:</strong>
      </p>
      <ol class="list-decimal list-inside ml-4 my-3 space-y-2">
        <li>
          Kayıtlı e-posta adresinizden info@myloungers.com adresine "Hesap Silme Talebi" konulu
          bir e-posta gönderilmesi.
        </li>
        <li>
          Talebin alınmasını takiben en geç 7 iş günü içerisinde hesabınız ve hesabınıza bağlı tüm veriler
          kalıcı olarak silinir.
        </li>
        <li>Silme işlemi tamamlandığında kullanıcıya teyit e-postası gönderilir.</li>
      </ol>
      <p class="mb-4 leading-relaxed">
        Yasal saklama yükümlülüğü bulunan veriler (fatura, ödeme kayıtları vb.), Türk vergi mevzuatı
        çerçevesinde belirlenen süreyle (10 yıla kadar) saklanmaya devam eder.
      </p>

      <h2>4. Madde - Platformun Rolü ve Sorumlulukları</h2>
      <h3>4.1. Platformun Rolü</h3>
      <p class="mb-4 leading-relaxed">
        My Loungers platformu, kullanıcılar ile otel, beach club ve benzeri işletmeler arasında şezlong
        rezervasyonu ve yiyecek-içecek siparişlerinin gerçekleştirilmesi amacıyla aracılık hizmeti sunan
        bir platformdur. Şirket, yalnızca bu hizmetlerin sağlanmasına yönelik olarak işletmeler ile
        kullanıcıları bir araya getiren bir aracı konumundadır.
      </p>
      <h3>4.2. Platformun Sorumluluk Sınırları</h3>
      <p class="mb-4 leading-relaxed">
        Platform, işletmelerin sunduğu hizmetlerin kalitesinden, doğruluğundan veya ifasından doğrudan
        sorumlu değildir. İşletme ile kullanıcı arasında doğabilecek uyuşmazlıklardan münhasıran taraflar
        sorumludur. Platform, kullanıcıların yapmış olduğu rezervasyon veya siparişlerde yanlış bilgi
        girişi, gecikme, iptal veya eksik işlem gibi durumlardan kaynaklanan zararlardan sorumlu
        tutulamaz.
      </p>
      <p class="mb-4 leading-relaxed">
        Ödeme işlemleri, Paratika Elektronik Ödeme ve Dağıtım Hizmetleri A.Ş. aracılığıyla
        gerçekleştirilir. Ödeme süreçlerinde meydana gelebilecek teknik aksaklıklar veya gecikmelerde,
        kullanıcı, doğrudan Ödeme Sağlayıcı ile iletişim kurmakla yükümlüdür.
      </p>
      <h3>4.3. Şirketin Yetkileri</h3>
      <p class="mb-4 leading-relaxed">
        Şirket, kullanıcı veya işletme tarafından sözleşmeye aykırı bir durum tespit edilmesi halinde
        ilgili hesabı geçici olarak askıya alma veya kalıcı olarak kapatma hakkını saklı tutar.
        Platformda yer alan içeriklerin (fiyat, menü, şezlong durumu vb.) doğruluğu ve güncelliği
        işletmelerin sorumluluğundadır.
      </p>
      <h3>4.4. Bağımsız Taraflar</h3>
      <p class="mb-4 leading-relaxed">
        Platformda yer alan tüm işlemler kullanıcı ile işletme arasında gerçekleştirilir. Şirket, bu
        işlemlerin tarafı olmayıp, yalnızca teknik altyapı ve aracılık hizmeti sunmaktadır.
      </p>

      <h2>5. Madde - Kullanıcı Hak ve Yükümlülükleri</h2>
      <h3>5.1. Kullanıcı Hakları</h3>
      <p class="mb-4 leading-relaxed">
        Kullanıcı, My Loungers platformuna kaydolduktan sonra platformda işletmeler tarafından sunulan
        hizmetlerden gerekli ücretlendirmeleri karşılayarak faydalanma hakkına sahiptir. Kullanıcı, KVKK
        kapsamında, platformda işlenen kişisel verilerine ilişkin bilgilendirilme, düzeltilme ve silinme
        haklarını kullanabilir.
      </p>
      <h3>5.2. Kullanıcı Yükümlülükleri</h3>
      <p class="mb-4 leading-relaxed">
        Kullanıcı, platforma kaydolurken verdiği tüm bilgilerin doğru, güncel ve eksiksiz olduğunu taahhüt
        eder. Yanlış veya eksik bilgi verilmesi durumunda doğacak tüm zararlardan kullanıcı sorumlu
        olacaktır. Kullanıcı, platformda kullandığı hesabının şifresini ve erişim bilgilerini gizli
        tutmakla yükümlüdür.
      </p>
      <p class="mb-4 leading-relaxed">
        Platformun kullanım koşulu olarak kullanıcıların 18 yaşından büyük olması gerekmektedir.
        Kullanıcı, platformda sunulan hizmetleri yalnızca kişisel kullanım amacıyla kullanmayı kabul eder
        ve platform üzerinden ticari faaliyet yürütmeyeceğini taahhüt eder.
      </p>
      <h3>5.3. Kullanıcı Davranış Politikası</h3>
      <p class="mb-4 leading-relaxed">
        Kullanıcı, platformu kullanırken yürürlükteki tüm yasalara, mevzuata ve platform kurallarına uygun
        davranmayı kabul eder. Diğer kullanıcılar ve işletmelerle olan etkileşimlerinde saygılı ve dürüst
        davranır. Hakaret, tehdit, rahatsız edici veya yasadışı içerik barındıran iletişimlerde bulunmamayı
        kabul eder.
      </p>

      <h2>6. Madde - Bakiye Yükleme ve Kullanım Koşulları</h2>
      <p class="mb-4 leading-relaxed">
        Kullanıcı, My Loungers platformunda sunulan hizmetlerden faydalanabilmek için platform üzerinden
        bakiye yükleyebilir. Bakiye yükleme işlemi, yalnızca kullanıcının kendisine ait veya yasal olarak
        kullanım hakkına sahip olduğu ödeme araçları ile yapılabilir.
      </p>
      <p class="mb-4 leading-relaxed">
        Ödeme işlemleri, Paratika Elektronik Ödeme ve Dağıtım Hizmetleri A.Ş. aracılığıyla güvenli bir
        şekilde gerçekleştirilir. Kullanıcı tarafından platforma yüklenen bakiye, yalnızca platformda
        sunulan hizmetler için kullanılabilir ve nakit olarak iade edilmez. Mesafeli Sözleşmeler
        Yönetmeliği'nin 15. maddesi uyarınca, bakiye yükleme işlemi cayma hakkı kapsamında değildir.
      </p>
      <p class="mb-4 leading-relaxed">
        Yüklenen bakiyenin kullanım süresi, platformda belirtilen hizmetlerin süresi ile sınırlıdır.
        Belirlenen süreler dahilinde kullanılmayan bakiye, platform politikaları kapsamında geçerliliğini
        yitirebilir.
      </p>

      <h2>7. Madde - Rezervasyon ve Sipariş Koşulları</h2>
      <p class="mb-4 leading-relaxed">
        Kullanıcı, My Loungers platformu üzerinden işletmelerin sunduğu şezlong rezervasyonu ve
        yiyecek-içecek siparişi gibi hizmetlerden faydalanabilir. Kullanıcı, işlem onaylanmadan önce
        hizmetin tarih, saat ve detaylarını dikkatlice kontrol etmekle yükümlüdür. Onaylanan işlemler,
        Mesafeli Sözleşmeler Yönetmeliği'nin 15. maddesi gereğince cayma hakkı kapsamına girmez.
      </p>
      <p class="mb-4 leading-relaxed">
        İptal veya değişiklik talepleri, yalnızca işletmenin belirlediği politika ve kurallara uygun şekilde
        yapılabilir. Platformda yapılan tüm işlemler, kullanıcı ve işletme arasında akdedilen Mesafeli
        Satış Sözleşmesi'ne tabidir.
      </p>

      <h2>8. Madde - İptal, Cayma Hakkı ve İade Koşulları</h2>
      <p class="mb-4 leading-relaxed">
        Kullanıcı, My Loungers platformu üzerinden yaptığı şezlong rezervasyonu veya yiyecek-içecek
        siparişi işlemlerinde, iptal ve iade hakkına sahip değildir. Mesafeli Sözleşmeler
        Yönetmeliği'nin 15. maddesi gereğince, belirli bir tarihte veya dönemde ifa edilmesi gereken
        hizmetlere ilişkin sözleşmelerde cayma hakkı bulunmamaktadır.
      </p>
      <p class="mb-4 leading-relaxed">
        Ancak, kullanıcı ile hizmeti sağlayan işletme arasında, tarafların karşılıklı anlaşması halinde
        iade veya iptal işlemleri gerçekleştirilmesi mümkündür. Bu durum, tamamen kullanıcı ile işletme
        arasındaki bir mutabakata dayanmakta olup, Şirket'in bu süreçlerde herhangi bir sorumluluğu
        bulunmamaktadır.
      </p>

      <h2>9. Madde - Ücretlendirme ve Komisyon Politikası</h2>
      <p class="mb-4 leading-relaxed">
        <strong>Komisyon Oranı:</strong> My Loungers platformu, işletmelerden sunulan hizmetler karşılığında
        %7 oranında komisyon almaktadır. Bu komisyon, hizmetin ifası sonrasında tahsil edilen toplam
        bedelden otomatik olarak düşülerek işletmeye aktarılır.
      </p>
      <p class="mb-4 leading-relaxed">
        <strong>Ödeme Süreçleri:</strong> Kullanıcılar tarafından yapılan ödemeler, platformun anlaşmalı
        olduğu ödeme sağlayıcı aracılığıyla tahsil edilir.
      </p>
      <p class="mb-4 leading-relaxed">
        <strong>İade Durumlarında Komisyon:</strong> Kullanıcı ile işletme arasında gerçekleşecek
        karşılıklı mutabakat sonucu herhangi bir iade yapılması durumunda, komisyon oranı iade tutarından
        düşülerek hesaplanır. Komisyon kesintisi iade edilemez.
      </p>

      <h2>10. Madde - Mobil Uygulama Kullanımı</h2>
      <h3>10.1. Uygulama Mağazaları</h3>
      <p class="mb-4 leading-relaxed">
        My Loungers mobil uygulaması, Apple App Store ve Google Play Store üzerinden indirilebilir.
        Kullanıcı, uygulamayı yalnızca resmi mağazalardan indirmekle yükümlüdür. Üçüncü taraf
        kaynaklarından indirilen uygulamalardan doğacak güvenlik açıkları, veri kayıpları ve sair
        zararlardan Şirket sorumlu tutulamaz.
      </p>
      <p class="mb-4 leading-relaxed">
        Kullanıcı, mobil uygulamayı kullanırken Apple App Store Hizmet Şartları ve Google Play Hizmet
        Şartlarına da uymakla yükümlüdür.
      </p>
      <h3>10.2. Cihaz İzinleri</h3>
      <p class="mb-4 leading-relaxed">
        Mobil uygulama, hizmetin sağlanabilmesi için aşağıdaki cihaz izinlerini talep edebilir:
      </p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>
          <strong>Konum (Location):</strong> Yakınınızdaki tesisleri göstermek ve harita üzerinde konum
          bazlı arama yapabilmek için. Reddedilebilir.
        </li>
        <li>
          <strong>Bildirimler (Notifications):</strong> Rezervasyon onayı, hatırlatma, ödeme
          bilgilendirmesi ve hizmete dair güncellemeleri iletmek için. Reddedilebilir.
        </li>
        <li>
          <strong>Kamera ve Galeri:</strong> Profil fotoğrafı yüklemek ve yorum süreçlerinde görsel
          paylaşımı için. Reddedilebilir.
        </li>
        <li>
          <strong>İnternet Erişimi:</strong> Uygulamanın temel fonksiyonlarının çalışması için zorunludur.
        </li>
      </ul>
      <h3>10.3. Uygulama Güncellemeleri</h3>
      <p class="mb-4 leading-relaxed">
        Şirket, mobil uygulamayı güvenlik, performans ve fonksiyonel iyileştirmeler amacıyla güncelleme
        hakkına sahiptir. Kullanıcı, uygulamanın güncel sürümünü kullanmakla yükümlüdür.
      </p>

      <h2>11. Madde - Üçüncü Taraf Servisler</h2>
      <p class="mb-4 leading-relaxed">
        Platform, hizmetin sağlanabilmesi için aşağıdaki üçüncü taraf servislerini kullanmaktadır. Bu
        servisler, kendi şartları ve gizlilik politikaları çerçevesinde hizmet vermektedir:
      </p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>
          <strong>Apple Sign-In:</strong> Apple kullanıcılarının kimlik doğrulaması için. Apple Inc.
          politikalarına tabidir.
        </li>
        <li>
          <strong>Google Sign-In:</strong> Google kullanıcılarının kimlik doğrulaması için. Google LLC
          politikalarına tabidir.
        </li>
        <li>
          <strong>Supabase (Frankfurt, Almanya):</strong> Kullanıcı verilerinin güvenli depolanması ve
          kimlik doğrulama altyapısı için. AB veri merkezinde saklanır.
        </li>
        <li>
          <strong>Paratika (Asseco SEE):</strong> Ödeme işlemlerinin güvenli gerçekleştirilmesi için.
          PCI-DSS standartlarına uygundur.
        </li>
      </ul>
      <p class="mb-4 leading-relaxed">
        Şirket, üçüncü taraf servislerin kendi politikalarından, hizmet kesintilerinden veya teknik
        aksaklıklarından doğacak zararlardan sorumlu tutulamaz.
      </p>

      <h2>12. Madde - Mücbir Sebepler</h2>
      <p class="mb-4 leading-relaxed">
        Doğal afetler, salgın hastalıklar, savaş, terör eylemleri, internet altyapısındaki kesintiler,
        elektrik kesintileri, siber saldırılar, üçüncü taraf servis sağlayıcıların kesintileri ve sair
        Şirketin kontrolü dışındaki olaylar mücbir sebep olarak kabul edilir. Mücbir sebep hallerinde,
        Şirket'in işbu sözleşmeden doğan yükümlülüklerini yerine getirememesi durumunda, Şirket
        sorumlu tutulamaz.
      </p>

      <h2>13. Madde - Bildirimler</h2>
      <p class="mb-4 leading-relaxed">
        Tarafların birbirine yapacağı tüm bildirimler, kullanıcının üyelik kaydında belirttiği e-posta
        adresine veya Şirket'in info@myloungers.com adresine yazılı olarak yapılabilir. E-posta
        yoluyla yapılan bildirimler, gönderim tarihinden itibaren 24 saat sonra yapılmış sayılır.
      </p>

      <h2>14. Madde - Sözleşme Değişiklikleri</h2>
      <p class="mb-4 leading-relaxed">
        Şirket, işbu sözleşmeyi tek taraflı olarak değiştirme ve güncelleme hakkını saklı tutar. Yapılan
        değişiklikler, platform üzerinde yayınlandığı tarihten itibaren geçerlilik kazanır. Kullanıcı,
        platformu kullanmaya devam etmesi halinde değişiklikleri kabul etmiş sayılır. Esaslı değişiklikler
        kullanıcılara e-posta yoluyla ayrıca bildirilir.
      </p>

      <h2>15. Madde - Uyuşmazlıkların Çözümü ve Yetkili Mahkeme</h2>
      <p class="mb-4 leading-relaxed">
        İşbu sözleşmenin uygulanmasından doğabilecek her türlü uyuşmazlığın çözümünde Türk Hukuku
        uygulanır. Uyuşmazlıkların çözümünde Sakarya Mahkemeleri ve İcra Daireleri yetkilidir.
      </p>
      <p class="mb-4 leading-relaxed">
        Tüketici uyuşmazlıklarında, Tüketicinin Korunması Hakkında Kanun ve ilgili mevzuat hükümleri
        uyarınca belirlenen parasal sınırlar dahilinde Tüketici Hakem Heyetleri ve Tüketici Mahkemeleri
        yetkilidir.
      </p>

      <h2>16. Madde - Yürürlük</h2>
      <p class="mb-4 leading-relaxed">
        İşbu sözleşme, kullanıcının platforma kayıt olması ve ilgili onay kutusunu işaretlemesi ile
        birlikte taraflar arasında yürürlüğe girer ve kullanıcının üyeliği devam ettiği sürece
        geçerliliğini korur. Sözleşme 16 (on altı) maddeden ibaret olup elektronik ortamda akdedilmiştir.
      </p>$yasal_kullanim_kosullari$,
  NULL
),
(
  'iptal-iade',
  'İptal ve İade Politikası',
  NULL,
  'MyLoungers iptal ve iade politikası — rezervasyon iptali ve ücret iadesi koşulları.',
  NULL,
  $yasal_iptal_iade$<p class="mb-4 leading-relaxed">
        My Loungers platformu üzerinden gerçekleştirdiğiniz şezlong rezervasyonları ve diğer hizmet
        satın alımlarına ilişkin iptal ve iade koşulları aşağıda detaylandırılmıştır. Lütfen rezervasyon
        yapmadan önce bu politikayı dikkatlice okuyunuz.
      </p>

      <h2>1. Cayma Hakkının Kapsamı</h2>
      <p class="mb-4 leading-relaxed">
        6502 sayılı Tüketicinin Korunması Hakkında Kanun ve Mesafeli Sözleşmeler
        Yönetmeliği'nin 15. maddesi uyarınca, belirli bir tarihte veya dönemde ifa edilmesi
        gereken hizmetler cayma hakkı istisnası kapsamındadır.
      </p>
      <p class="mb-4 leading-relaxed">
        My Loungers platformu üzerinden yapılan şezlong rezervasyonları ve yiyecek-içecek siparişleri,
        belirli bir tarih ve saatte ifa edilen hizmetler olduğundan, kullanıcı cayma hakkını
        kullanamaz. Bu nedenle:
      </p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>Yapılan rezervasyonlar kesindir ve kullanıcı tarafından tek taraflı olarak iptal edilemez.</li>
        <li>Ödeme iadesi talep edilemez.</li>
        <li>Rezervasyon onayı verildikten sonra herhangi bir nedenle ücret iadesi yapılmaz.</li>
      </ul>

      <h2>2. İşletme ile Mutabakat Yoluyla İptal</h2>
      <p class="mb-4 leading-relaxed">
        Yukarıdaki kural saklı kalmak kaydıyla, kullanıcı ile rezervasyonun yapıldığı işletme arasında
        karşılıklı mutabakat sağlanması halinde iptal veya iade işlemi gerçekleştirilebilir. Bu durum
        tamamen kullanıcı ile işletme arasındaki anlaşmaya bağlıdır.
      </p>
      <p class="mb-4 leading-relaxed">
        My Loungers platformu, bu süreçlerde aracılık görevi üstlenmez ve kullanıcı ile işletmeyi
        uzlaştırma yükümlülüğü bulunmamaktadır. İade gerçekleştirilmesi durumunda %7'lik komisyon
        kesintisi iade tutarından düşülerek hesaplanır ve komisyon kesintisi iade edilmez.
      </p>

      <h2>3. Mücbir Sebep Hallerinde İptal</h2>
      <p class="mb-4 leading-relaxed">
        Doğal afet, salgın hastalık, olağanüstü hava koşulları (fırtına, sağanak yağış vb.), elektrik
        kesintileri veya benzeri mücbir sebeplerle hizmetin ifasının imkansız hale gelmesi durumunda:
      </p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>İşletme, rezervasyonu farklı bir tarihe öteleyebilir veya iade gerçekleştirebilir.</li>
        <li>İade kararı işletmenin takdir yetkisindedir.</li>
        <li>Platform, mücbir sebep hallerinden kaynaklanan iptallerden sorumlu tutulamaz.</li>
      </ul>

      <h2>4. İşletmeden Kaynaklanan İptaller</h2>
      <p class="mb-4 leading-relaxed">
        Rezervasyon yapılan işletmenin kapanması, hizmeti sunamaması veya rezervasyonu reddetmesi gibi
        işletme kaynaklı durumlarda:
      </p>
      <ol class="list-decimal list-inside ml-4 my-3 space-y-2">
        <li>İşletme, kullanıcıya derhal bildirim yapmakla yükümlüdür.</li>
        <li>Ödenen tutar kullanıcıya tam olarak iade edilir.</li>
        <li>
          İade işlemi, ödemenin yapıldığı kart/hesap üzerinden, ödeme sağlayıcının prosedürlerine göre
          7-14 iş günü içerisinde gerçekleştirilir.
        </li>
        <li>Platform, bu süreçte aracılık görevini üstlenir.</li>
      </ol>

      <h2>5. Bakiye İadesi</h2>
      <p class="mb-4 leading-relaxed">
        Kullanıcı tarafından platforma yüklenen bakiye, yalnızca platformda sunulan hizmetler için
        kullanılabilir ve nakit olarak iade edilmez. Mesafeli Sözleşmeler Yönetmeliği'nin 15.
        maddesi uyarınca, bakiye yükleme işlemi cayma hakkı kapsamı dışındadır.
      </p>
      <p class="mb-4 leading-relaxed">
        Yüklenen bakiyenin kullanım süresi, platformda belirtilen hizmetlerin süresi ile sınırlıdır.
        Belirlenen süreler dahilinde kullanılmayan bakiye, platform politikaları kapsamında geçerliliğini
        yitirebilir.
      </p>

      <h2>6. İade Süreci ve Süreler</h2>
      <p class="mb-4 leading-relaxed">
        <strong>İade süreci şu adımlarla işler:</strong>
      </p>
      <ol class="list-decimal list-inside ml-4 my-3 space-y-2">
        <li>İşletme ile iade konusunda mutabakat sağlanır veya işletme tarafından iade kararı verilir.</li>
        <li>İşletme, iade talebini Platform'a iletir.</li>
        <li>Platform, iade işlemini ödeme sağlayıcı (Paratika) üzerinden başlatır.</li>
        <li>İade tutarı, ödemenin yapıldığı kart/hesaba 7-14 iş günü içerisinde aktarılır.</li>
      </ol>
      <p class="mb-4 leading-relaxed">
        İade süresi, ödeme sağlayıcı ve banka prosedürlerine bağlıdır. Platform'un bu süre
        üzerinde doğrudan bir etkisi bulunmamaktadır.
      </p>

      <h2>7. İade Yapılamayacak Durumlar</h2>
      <p class="mb-4 leading-relaxed">Aşağıdaki durumlarda iade gerçekleştirilemez:</p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>Kullanıcının rezervasyon saatinde tesiste bulunmaması (no-show).</li>
        <li>Kullanıcının yanlış bilgi vererek rezervasyon yapması.</li>
        <li>Hizmetin ifa edilmiş olması (şezlongun kullanılmış olması).</li>
        <li>İşletme kurallarının ihlal edilmesi nedeniyle hizmetin sonlandırılması.</li>
        <li>Rezervasyon tarihinin geçmiş olması.</li>
      </ul>

      <h2>8. İletişim ve Talep Bildirimi</h2>
      <p class="mb-4 leading-relaxed">
        İptal, iade veya rezervasyon ile ilgili sorun ve talepleriniz için aşağıdaki kanallardan bizimle
        iletişime geçebilirsiniz:
      </p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>
          <strong>E-posta:</strong> info@myloungers.com
        </li>
        <li>
          <strong>Web:</strong> www.myloungers.com
        </li>
        <li>
          <strong>Adres:</strong> Esentepe Mah. Akademiyolu Sok. Teknoloji Geliştirme Bölgesi No:10B/B01
          Serdivan/SAKARYA
        </li>
      </ul>
      <p class="mb-4 leading-relaxed">
        Talepleriniz en geç 7 iş günü içerisinde değerlendirilerek tarafınıza dönüş yapılır.
      </p>

      <h2>9. Tüketici Hakları</h2>
      <p class="mb-4 leading-relaxed">
        Kullanıcılar, 6502 sayılı Tüketicinin Korunması Hakkında Kanun kapsamında sahip oldukları tüm
        haklarını saklı tutar. Tüketici uyuşmazlıklarında, kanunda belirtilen parasal sınırlar
        dahilinde:
      </p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>Tüketici Hakem Heyetleri'ne başvuru yapılabilir.</li>
        <li>Tüketici Mahkemeleri yetkilidir.</li>
      </ul>
      <p class="mb-4 leading-relaxed">
        Yetkili mahkemeler, kullanıcının yerleşim yerindeki Tüketici Mahkemeleri'dir.
      </p>$yasal_iptal_iade$,
  NULL
),
(
  'cerez-politikasi',
  'Çerez Politikası',
  NULL,
  'MyLoungers çerez politikası — çerez türleri, kullanım amaçları ve tercihleriniz.',
  NULL,
  $yasal_cerez_politikasi$<p class="mb-4 leading-relaxed">
        My Loungers olarak www.myloungers.com internet sitesi ve mobil uygulamamız içerisinde yer alan
        bazı alanlarda çerezler kullanmaktayız. Bu Çerez Politikası, Reklamotv Bilişim Teknoloji
        Reklamcılık ve Organizasyon Hiz. San. ve Tic. Ltd. Şti. tarafından yönetilen işbu site için
        geçerli olup çerezler; siteyi ziyaretiniz sırasında politikada açıklanan şekilde kullanılacaktır.
      </p>

      <h2>1. Çerez Nedir</h2>
      <p class="mb-4 leading-relaxed">
        Çerezler, www.myloungers.com tarafından cihazınızda saklanan küçük metin dosyalarıdır ve siteye
        erişim sağladığınız tarayıcıda tutulur. Bu dosyalar, sitemizi ziyaret ettiğinizde bilgilerinizi
        hatırlamak ve deneyiminizi kişiselleştirip memnuniyetinizi artırmak için kullanılır. Çerezler,
        kullanıcı tercihlerini kaydetmek ve cihazınızı tanımak gibi temel işlevler sunar. Bu nedenle,
        çerezler sitemizin düzgün çalışabilmesi ve size daha iyi bir hizmet sunulabilmesi için
        gereklidir.
      </p>

      <h2>2. Çerez Türleri ve Açıklamaları</h2>
      <ol class="list-decimal list-inside ml-4 my-3 space-y-2">
        <li>
          <strong>Oturum Çerezleri:</strong> Siteyi kullanımınız sırasında geçerlidir ve tarayıcı
          kapatılana kadar aktif kalır.
        </li>
        <li>
          <strong>Kalıcı Çerezler:</strong> Tarayıcınıza kaydedilen bu çerezler, silinene kadar veya
          belirlenen tarihe kadar geçerlidir.
        </li>
        <li>
          <strong>Birinci Taraf Çerezleri:</strong> Site tarafından oluşturulur ve sadece site tarafından
          okunabilir. Oturum veya kalıcı çerez olabilir.
        </li>
        <li>
          <strong>Üçüncü Taraf Çerezleri:</strong> Platformlar üzerinden sağlanan içeriklerin
          çerezleridir. Genellikle kalıcıdırlar ve üçüncü taraf hizmet sağlayıcıları tarafından
          kullanılır.
        </li>
      </ol>

      <h2>3. Çerezlerin Kullanım Amaçları</h2>
      <p class="mb-4 leading-relaxed">
        <strong>Zorunlu Çerezler:</strong> Bu çerezler, www.myloungers.com'un düzgün çalışabilmesi ve
        sunduğu hizmetlerden faydalanabilmeniz için zorunlu çerezlerdir, site kullanımı için olmazsa
        olmazdır. Kişisel veriler bu çerezler aracılığıyla kesinlikle işlenmemektedir.
      </p>
      <p class="mb-4 leading-relaxed">
        <strong>Performans Çerezleri:</strong> Site performansını ölçmek ve geliştirmek amacıyla
        ziyaretçilerimizin internet sitemizin içerisinde hangi sayfalarda zaman geçirdiklerini görmemize
        yardımcı olur. Toplanan bilgiler anonim olup, sadece siteyi iyileştirmek amacıyla kullanılır.
      </p>
      <p class="mb-4 leading-relaxed">
        <strong>İşlevsellik Çerezleri:</strong> Kullanıcıların dil ve bölge tercihleri gibi
        kişiselleştirilmiş ayarlarını hatırlamak için kullanılır. Bu çerezlerin devre dışı bırakılması
        durumunda, kişiselleştirilmiş ayarlar kaydedilemez.
      </p>
      <p class="mb-4 leading-relaxed">
        <strong>Hedefleme Çerezleri:</strong> www.myloungers.com ve üçüncü taraf sitelerdeki ziyaretleriniz
        sırasında oluşturulur. Tıklama ve ziyaret geçmişinizi izlemek, profil oluşturmak, reklam ve
        pazarlama stratejileri geliştirmek amacıyla kullanılır.
      </p>
      <p class="mb-4 leading-relaxed">
        Bu çerezlerin kullanımı esnasında gerçekleştirdiğimiz veri işleme faaliyetleri için KVKK Madde 5
        kapsamında "İlgili kişinin temel hak ve özgürlüklerine zarar vermemek kaydıyla, veri
        sorumlusunun meşru menfaatleri için veri işlenmesinin zorunlu olması" hükmüne
        dayanmaktayız.
      </p>

      <h2>4. Platformda Kullanılan Çerezler</h2>
      <p class="mb-4 leading-relaxed">
        My Loungers platformunda kullanılan çerezler ve bu çerezlerin amaçları aşağıdaki tabloda
        detaylandırılmıştır:
      </p>

      <div class="overflow-x-auto my-6">
        <table class="w-full text-sm border-collapse">
          <thead>
            <tr>
              <th class="border border-gray-300 dark:border-gray-700 bg-[#0ABAB5] text-white px-3 py-2 text-left font-semibold">
                Çerez Adı / Kaynak
              </th>
              <th class="border border-gray-300 dark:border-gray-700 bg-[#0ABAB5] text-white px-3 py-2 text-left font-semibold">
                Amacı
              </th>
              <th class="border border-gray-300 dark:border-gray-700 bg-[#0ABAB5] text-white px-3 py-2 text-left font-semibold">
                Türü
              </th>
              <th class="border border-gray-300 dark:border-gray-700 bg-[#0ABAB5] text-white px-3 py-2 text-left font-semibold">
                Süre
              </th>
              <th class="border border-gray-300 dark:border-gray-700 bg-[#0ABAB5] text-white px-3 py-2 text-left font-semibold">
                Zorunlu
              </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Supabase Auth Token
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Kullanıcı kimlik doğrulaması ve oturum yönetimi
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Birinci Taraf / Zorunlu
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Oturum + 30 gün
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">Evet</td>
            </tr>
            <tr>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                session_id
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Site içi gezinme sırasında oturum sürekliliği
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Birinci Taraf / Zorunlu
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">Oturum</td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">Evet</td>
            </tr>
            <tr>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                language / locale
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Dil tercihinin (TR / EN) hatırlanması
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Birinci Taraf / İşlevsel
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">1 yıl</td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">Hayır</td>
            </tr>
            <tr>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                cookie_consent
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Çerez tercihlerinizin hatırlanması
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Birinci Taraf / Zorunlu
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">1 yıl</td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">Evet</td>
            </tr>
            <tr>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Paratika Ödeme Çerezleri
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Ödeme işlemlerinin güvenli gerçekleştirilmesi
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Üçüncü Taraf / Zorunlu
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">Oturum</td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Evet (ödeme anında)
              </td>
            </tr>
            <tr>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Apple / Google Sign-In Çerezleri
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Apple ve Google ile giriş kimlik doğrulaması
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Üçüncü Taraf / Zorunlu
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">Oturum</td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Evet (giriş anında)
              </td>
            </tr>
            <tr>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Performans / Analitik Çerezleri
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Site kullanım istatistikleri ve performans iyileştirme
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                Birinci Taraf / Performans
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">
                2 yıla kadar
              </td>
              <td class="border border-gray-300 dark:border-gray-700 px-3 py-2 align-top">Hayır</td>
            </tr>
          </tbody>
        </table>
      </div>

      <p class="mb-4 leading-relaxed">
        Yukarıdaki çerezlerin yanı sıra, üçüncü taraf hizmet sağlayıcılar (ödeme işlemleri için
        Paratika, kimlik doğrulama için Apple Sign-In ve Google Sign-In) tarafından kendi politikaları
        çerçevesinde çerezler yerleştirilebilir. Bu çerezlerin kontrolü ve yönetimi ilgili üçüncü taraf
        hizmet sağlayıcılara aittir.
      </p>

      <h2>5. Çerez Yönetimi ve Çerez Yönetiminin Sınırlandırılması</h2>
      <p class="mb-4 leading-relaxed">
        Tarayıcılar genellikle çerezleri otomatik olarak kabul eder. www.myloungers.com'u
        kullanabilmek için çerezlerin kullanımı zorunlu değildir, ancak tarayıcınızı çerezleri kabul
        etmeyecek şekilde ayarlamanız durumunda kullanıcı deneyiminiz olumsuz etkilenebilir ve sitemizin
        bazı işlevleri düzgün çalışmayabilir.
      </p>
      <p class="mb-4 leading-relaxed">
        Tarayıcınızı; tüm siteler veya belirli siteler için çerezleri engelleyecek, çerez oluşturulduğunda
        uyarı verecek, üçüncü taraf çerezleri engelleyecek veya tüm çerezleri oturum çerezi gibi kabul
        edecek şekilde ayarlayabilirsiniz. Ayrıca tarayıcınızda saklanan çerezleri silebilir veya bunların
        listesini ve içeriklerini görüntüleyebilirsiniz.
      </p>
      <p class="mb-4 leading-relaxed">
        <strong>Popüler tarayıcılarda çerez yönetimi:</strong>
      </p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>
          <strong>Google Chrome:</strong> support.google.com/chrome
        </li>
        <li>
          <strong>Mozilla Firefox:</strong> support.mozilla.org
        </li>
        <li>
          <strong>Safari:</strong> support.apple.com
        </li>
        <li>
          <strong>Microsoft Edge:</strong> support.microsoft.com
        </li>
      </ul>

      <h2>6. Mobil Uygulamada Çerez ve Benzeri Teknolojiler</h2>
      <p class="mb-4 leading-relaxed">
        My Loungers mobil uygulamasında, web tarayıcı çerezleri yerine cihaz hafızasında saklanan benzer
        teknolojiler (local storage, secure storage, oturum tokenları) kullanılmaktadır. Bu teknolojiler,
        kullanıcı oturumunun sürdürülmesi, tercih ayarlarının (dil seçimi vb.) hatırlanması ve uygulamanın
        doğru çalışması için gereklidir.
      </p>
      <p class="mb-4 leading-relaxed">
        Mobil uygulama içinde saklanan veriler, uygulama silindiğinde veya cihaz ayarlarından uygulama
        verileri temizlendiğinde otomatik olarak silinir.
      </p>

      <h2>7. Çerezlerin Aktarılması</h2>
      <p class="mb-4 leading-relaxed">
        Çerezler kapsamında işlenen verileriniz, www.myloungers.com hizmetlerinin size özelleştirilerek
        sunulması, pazarlama faaliyetlerinin yürütülmesi, iş süreçlerinin takibi ve denetimi, mal/hizmet
        satın alma süreçlerinin yürütülmesi gibi amaçlarla kullanılabilir.
      </p>
      <p class="mb-4 leading-relaxed">
        Bu metni onaylayan kullanıcılar, çerezlerle elde edilen verilerin belirtilen kapsam ve şartlar
        dahilinde üçüncü kişilerle paylaşılacağını kabul eder.
      </p>

      <h2>8. Çerezlerin Saklama Süreleri</h2>
      <p class="mb-4 leading-relaxed">Çerezler türlerine göre farklı sürelerde saklanır:</p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>
          <strong>Oturum çerezleri:</strong> Tarayıcı kapatıldığında otomatik olarak silinir.
        </li>
        <li>
          <strong>Kalıcı çerezler:</strong> Belirlenen geçerlilik süresi sonunda veya kullanıcı tarafından
          manuel olarak silinene kadar saklanır.
        </li>
        <li>
          <strong>Kimlik doğrulama çerezleri:</strong> Oturum aktif olduğu sürece ve en fazla 30 gün
          boyunca saklanır.
        </li>
        <li>
          <strong>Tercih çerezleri:</strong> 1 yıla kadar saklanabilir.
        </li>
        <li>
          <strong>Performans/analitik çerezleri:</strong> 2 yıla kadar saklanabilir.
        </li>
      </ul>
      <p class="mb-4 leading-relaxed">
        Saklama süresi sona eren çerezler otomatik olarak silinir veya tekrar oluşturulmaz.
      </p>

      <h2>9. Politika Güncellemeleri</h2>
      <p class="mb-4 leading-relaxed">
        www.myloungers.com işbu çerez politikasını değiştirme hakkını saklı tutar. Yapılan değişiklikler,
        platform üzerinde yayınlandığı tarihten itibaren geçerlilik kazanır. Önemli değişiklikler
        kullanıcılara ayrıca bildirilir.
      </p>

      <h2>10. İletişim Bilgileri</h2>
      <p class="mb-4 leading-relaxed">
        Çerez politikasına ilişkin soru, talep ve şikayetleriniz için bizimle iletişime geçebilirsiniz:
      </p>
      <ul class="list-disc list-inside ml-4 my-3 space-y-2">
        <li>
          <strong>E-posta:</strong> info@myloungers.com
        </li>
        <li>
          <strong>Posta Adresi:</strong> Esentepe Mah. Akademiyolu Sok. Teknoloji Geliştirme Bölgesi
          No:10B/B01 Serdivan/SAKARYA
        </li>
        <li>
          <strong>Web:</strong> www.myloungers.com
        </li>
      </ul>$yasal_cerez_politikasi$,
  NULL
)
ON CONFLICT (slug) DO UPDATE SET
  baslik = EXCLUDED.baslik,
  meta_aciklama = EXCLUDED.meta_aciklama,
  icerik = EXCLUDED.icerik;
